development:
  default_url_options:
    host: localhost:3000
    protocol: http
  default_event_coordinates: { lat: 24.45092, lng: 118.0827}

test:
  default_url_options:
    host: localhost:3000
    protocol: http

staging:

production:
